"""
Django settings for ThemeMart project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

# useful commands for this project
# py manage.py runserver 0.0.0.0:8000
# pip freeze > requirements.txt
# razorpay_payment success = success@razorpay , failure = failure@razorpay
# https://stackoverflow.com/questions/37255548/how-to-run-celery-on-windows
# celery -A ThemeMart beat -l info
# celery -A ThemeMart worker -l info -P eventlet
# celery -A ThemeMart purge

from pathlib import Path
import os
from django.contrib import messages # type: ignore
from django.urls import reverse_lazy # type: ignore
from . import credential

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
TEMPLATE_DIR = os.path.join(BASE_DIR, 'templates')
STATIC_DIR = os.path.join(BASE_DIR, 'static')
MEDIA_DIR = os.path.join(BASE_DIR, 'media')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '++835ejt_@1(v2=5j+mg#-%fe3%!t0hdhl7fo4qyw#%f99v4!r'
SECRET_KEY_FALLBACKS = [
    'g_@ls&q=34@^ww$0gi6)ns0843g_cy2((j!&b&52u8r!$nmu3s',
    'w7#gukgxe1nnh(g0=nx_b6urh(iyj%l99f^f!wqh-4_@z1_7hp',
]

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    "127.0.0.1",
]


# Application definition

INSTALLED_APPS = [
    # django-jazzmin
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    # 'django.contrib.sessions',
    # django-qsessions
    'qsessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'django.contrib.sites',
    'django.contrib.sitemaps',
    
    # myApps
    'main.apps.MainConfig',
    'accounts.apps.AccountsConfig',
    'seller.apps.SellerConfig',
    'license.apps.LicenseConfig',
    'assets.apps.AssetsConfig',
    'orders.apps.OrdersConfig',
    
    # django-debug-toolbar
    "debug_toolbar",
    # django-phonenumber-field
    "phonenumber_field",
    # django-private-storage
    'private_storage',
    # django-taggit
    "taggit",
    # django-htmx
    "django_htmx",
    # django-celery-results
    'django_celery_results',
    # django-celery-beat
    'django_celery_beat',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # 'django.contrib.sessions.middleware.SessionMiddleware',
    # django-qsessions
    'qsessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
    # Django Debug Toolbar
    "debug_toolbar.middleware.DebugToolbarMiddleware",
    # django-htmx
    "django_htmx.middleware.HtmxMiddleware",
    # htmx-message-middleware
    "main.middleware.HtmxMessageMiddleware",
]

ROOT_URLCONF = 'ThemeMart.urls'
# django-qsessions
SESSION_ENGINE = 'qsessions.backends.cached_db'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATE_DIR],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # {{ MEDIA_URL }}
                'django.template.context_processors.media',
                'main.context_processors.get_asset_categories',
            ],
        },
    },
]

WSGI_APPLICATION = 'ThemeMart.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql', 
        'NAME': 'thememart',
        'USER': 'root',
        'PASSWORD': '',
        'HOST': 'localhost', 
        'PORT': '3306',
    }
}

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        },
        "TIMEOUT" : 120,
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS':{
            'min_length' : 8,
        },
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
    # custom password validators
    {
        'NAME': 'accounts.validators.NumberValidator',
    },
    {
        'NAME': 'accounts.validators.UppercaseValidator',
    },
    {
        'NAME': 'accounts.validators.LowercaseValidator',
    },
    {
        'NAME': 'accounts.validators.SymbolValidator',
    },
]

PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.Argon2PasswordHasher',
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
    'django.contrib.auth.hashers.BCryptPasswordHasher',
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
]

AUTH_USER_MODEL = "accounts.User"

LOGIN_URL = reverse_lazy("accounts:login")
BECOME_SELLER_URL = reverse_lazy("seller:become_seller")

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [STATIC_DIR,]
# STATIC_ROOT = STATIC_DIR

MEDIA_ROOT = MEDIA_DIR
MEDIA_URL = "media/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# SMTP Configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = credential.EMAIL_HOST_USER
EMAIL_HOST_PASSWORD = credential.EMAIL_HOST_PASSWORD

# django-debug-toolbar
INTERNAL_IPS = [
    "127.0.0.1",
]

# django-resized
DJANGORESIZED_DEFAULT_NORMALIZE_ROTATION = False
DJANGORESIZED_DEFAULT_QUALITY = 100
DJANGORESIZED_DEFAULT_KEEP_META = True

# django-messages
MESSAGE_TAGS = {
    messages.INFO: "text-white bg-black",
    messages.SUCCESS: "text-white bg-success",
    messages.WARNING: "text-dark bg-warning",
}

# django-phonenumber-field
PHONENUMBER_DEFAULT_FORMAT = 'NATIONAL'
PHONENUMBER_DEFAULT_REGION = 'IN'

# django-private-storage
PRIVATE_STORAGE_ROOT = os.path.join(BASE_DIR, 'private_media')
PRIVATE_STORAGE_AUTH_FUNCTION = 'private_storage.permissions.allow_superuser'

# django-taggit
TAGGIT_CASE_INSENSITIVE = False

SITE_DOMAIN = '192.168.1.45:8000'

# razorpay configuration
RAZORPAY_KEY_ID = credential.RAZORPAY_KEY_ID
RAZORPAY_KEY_SECRET = credential.RAZORPAY_KEY_SECRET


# Celery Configuration Options
CELERY_TIMEZONE = "Asia/Kolkata"
CELERY_BROKER_URL =  "redis://127.0.0.1:6379"
# django-celery-results
CELERY_RESULT_BACKEND = 'django-db'
CELERY_RESULT_EXTENDED = True
# CELERY_CACHE_BACKEND = 'default'
CELERYBEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'

# django-jazzmin configurations
JAZZMIN_SETTINGS = {
    # title of the window (Will default to current_admin_site.site_title if absent or None)
    "site_title": "ThemeMart Admin",

    # Title on the login screen (19 chars max) (defaults to current_admin_site.site_header if absent or None)
    "site_header": "ThemeMart",

    # Title on the brand (19 chars max) (defaults to current_admin_site.site_header if absent or None)
    "site_brand": "ThemeMart",

    # Logo to use for your site, must be present in static files, used for brand on top left
    "site_logo": "images/favicon_TM.png",

    # Logo to use for your site, must be present in static files, used for login form logo (defaults to site_logo)
    "login_logo": "images/logo.png",

    # Logo to use for login form in dark themes (defaults to login_logo)
    "login_logo_dark":"images/logo.png",

    # CSS classes that are applied to the logo above
    "site_logo_classes": "img-square",

    # Relative path to a favicon for your site, will default to site_logo if absent (ideally 32x32 px)
    "site_icon": "images/favicon_TM.png",

    # Welcome text on the login screen
    "welcome_sign": "Welcome to the ThemeMart Admin",

    # Copyright on the footer
    "copyright": "ThemeMart Pvt Ltd",

    # List of model admins to search from the search bar, search bar omitted if excluded
    # If you want to use a single search field you dont need to use a list, you can use a simple string 
    "search_model": ["accounts.User", "assets.Asset", 'orders.Orders'],

    # Field name on user model that contains avatar ImageField/URLField/Charfield or a callable that receives the user
    "user_avatar": 'profile_image',

    ############
    # Top Menu #
    ############

    # Links to put along the top menu
    "topmenu_links": [

        # Url that gets reversed (Permissions can be added)
        {"name": "Home",  "url": "admin:index"},

        # external url that opens in a new window (Permissions can be added)
        {"name": "View Site", "url": "main:home", "new_window": False},
    ],

    #############
    # User Menu #
    #############

    # Additional links to include in the user menu on the top right ("app" url type is not allowed)
    "usermenu_links": [
        {"name": "ThemeMart Dashboard", "url": "main:thememart_dashboard", "new_window": False},
    #     {"model": "auth.user"}
    ],

    #############
    # Side Menu #
    #############

    # Whether to display the side menu
    "show_sidebar": True,

    # Whether to aut expand the menu
    "navigation_expanded": True,

    # Hide these apps when generating side menu e.g (auth)
    "hide_apps": [],

    # Hide these models when generating side menu (e.g auth.user)
    "hide_models": [],

    # List of apps (and/or models) to base side menu ordering off of (does not need to contain all apps/models)
    "order_with_respect_to": ["main", "accounts", "license", "license.License_Term", "license.License", "assets", 'assets.Asset_Category', 'assets.Asset', 'assets.Asset_Preview_Images', 'orders', 'orders.Orders', 'seller', 'taggit','qsessions', 'sites'],

    # Custom links to append to app groups, keyed on app name
    # "custom_links": {
    #     "books": [{
    #         "name": "Make Messages", 
    #         "url": "make_messages", 
    #         "icon": "fas fa-comments",
    #         "permissions": ["books.view_book"]
    #     }]
    # },

    # Custom icons for side menu apps/models See https://fontawesome.com/icons?d=gallery&m=free&v=5.0.0,5.0.1,5.0.10,5.0.11,5.0.12,5.0.13,5.0.2,5.0.3,5.0.4,5.0.5,5.0.6,5.0.7,5.0.8,5.0.9,5.1.0,5.1.1,5.2.0,5.3.0,5.3.1,5.4.0,5.4.1,5.4.2,5.13.0,5.12.0,5.11.2,5.11.1,5.10.0,5.9.0,5.8.2,5.8.1,5.7.2,5.7.1,5.7.0,5.6.3,5.5.0,5.4.2
    # for the full list of 5.13.0 free icon classes
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
    },
    # Icons that are used when one is not manually specified
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",

    #################
    # Related Modal #
    #################
    # Use modals instead of popups
    "related_modal_active": True,

    #############
    # UI Tweaks #
    #############
    # Relative paths to custom CSS/JS scripts (must be present in static files)
    "custom_css": None,
    "custom_js": None,
    # Whether to link font from fonts.googleapis.com (use custom_css to supply font otherwise)
    "use_google_fonts_cdn": True,
    # Whether to show the UI customizer on the sidebar
    "show_ui_builder": True,

    ###############
    # Change view #
    ###############
    # Render out the change view as a single form, or in tabs, current options are
    # - single
    # - horizontal_tabs (default)
    # - vertical_tabs
    # - collapsible
    # - carousel
    "changeform_format": "horizontal_tabs",
    # override change forms on a per modeladmin basis
    "changeform_format_overrides": {"auth.user": "collapsible", "auth.group": "vertical_tabs"},
    # Add a language dropdown into the admin
    # "language_chooser": True,
}
JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": False,
    "accent": "accent-primary",
    "navbar": "navbar-white navbar-light",
    "no_navbar_border": False,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": False,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "lux",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-outline-primary",
        "secondary": "btn-outline-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    },
    "actions_sticky_top": True
}

# to run django-jazzmin's related_modal_active = True
X_FRAME_OPTIONS = 'SAMEORIGIN'

# Security
# SESSION_COOKIE_SECURE = True
# CSRF_COOKIE_SECURE = True
ADMINS = [
    ("Maulik", "maulikthumar785@gmail.com"),
]
FILE_UPLOAD_MAX_MEMORY_SIZE = 524288000 #(500MB) (2621440 = 2.5 MB).
NUMBER_GROUPING = (3, 2, 0)


SITE_ID = 1