# Generated by Django 5.0.6 on 2024-07-23 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='bank_account_ifsc_code',
            field=models.CharField(default='JBUCBUDV58956', max_length=100, verbose_name='Bank Account IFSC Code'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seller',
            name='bank_account_number',
            field=models.CharField(default=2645, max_length=100, verbose_name='Bank Account Number'),
            preserve_default=False,
        ),
    ]
