# Generated by Django 5.0.6 on 2024-07-27 11:57

import django.db.models.deletion
import django.utils.timezone
import seller.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0023_alter_asset_preview_images_options'),
        ('orders', '0014_alter_order_items_asset_and_more'),
        ('seller', '0004_seller_aadhar_card_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seller',
            options={'ordering': ['-date_created'], 'verbose_name': 'Seller', 'verbose_name_plural': 'Sellers'},
        ),
        migrations.AddField(
            model_name='seller',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name=' Date Created'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='seller',
            name='aadhar_card_number',
            field=models.CharField(max_length=50, validators=[seller.validators.aadhar_card_number_validator], verbose_name='Aadhar Card Number'),
        ),
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.UUID('2a28ed7c-b43c-4c3f-afca-b91a5f4344cc'), unique=True, verbose_name='UUID')),
                ('asset_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Asset Price')),
                ('razorpay_payment_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Razorpay Payment Fee')),
                ('razorpay_payment_tax', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Razorpay Payment Tax')),
                ('thememart_commision', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ThemeMart Commision')),
                ('final_sell', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Final Sale Amount')),
                ('paid', models.BooleanField(default=False, verbose_name='Is Paid?')),
                ('paid_on', models.DateTimeField(blank=True, null=True, verbose_name='Paid On')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.asset', verbose_name='Asset')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.orders', verbose_name='Order')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order_items', verbose_name=' Order Item')),
            ],
            options={
                'verbose_name': 'Sell',
                'verbose_name_plural': 'Sells',
                'ordering': ['-date_created'],
            },
        ),
    ]
