# Generated by Django 5.0.6 on 2024-07-27 12:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0005_alter_seller_options_seller_date_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sell',
            name='razorpay_payment_fee',
        ),
        migrations.RemoveField(
            model_name='sell',
            name='razorpay_payment_tax',
        ),
        migrations.AlterField(
            model_name='sell',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('76c40bf9-80f6-46dd-bf78-3a3caa3fbf66'), unique=True, verbose_name='UUID'),
        ),
    ]
