# Generated by Django 5.0.6 on 2024-07-27 12:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0006_remove_sell_razorpay_payment_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sell',
            name='razorpay_payment_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Razorpay Payment Fee'),
        ),
        migrations.AddField(
            model_name='sell',
            name='razorpay_payment_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Razorpay Payment Tax'),
        ),
        migrations.AlterField(
            model_name='sell',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('7b529df1-87ec-4f77-ba9b-7553efd7786f'), unique=True, verbose_name='UUID'),
        ),
    ]
