# Generated by Django 5.0.6 on 2024-07-27 12:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0007_sell_razorpay_payment_fee_sell_razorpay_payment_tax_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sell',
            name='razorpay_payment_fee',
        ),
        migrations.RemoveField(
            model_name='sell',
            name='razorpay_payment_tax',
        ),
        migrations.AddField(
            model_name='sell',
            name='razorpay_payment_commision',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Razorpay Payment Commision'),
        ),
        migrations.AlterField(
            model_name='sell',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('a4d35d6c-dc92-42e9-8302-8c2f1e3047b5'), unique=True, verbose_name='UUID'),
        ),
    ]
