# Generated by Django 5.0.6 on 2024-07-28 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0023_alter_asset_preview_images_options'),
        ('seller', '0009_sell_seller_alter_sell_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sells', to='assets.asset', verbose_name='Asset'),
        ),
    ]
