# Generated by Django 5.0.6 on 2024-07-05 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset_category',
            name='max_asset_size',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Maximum Asset Size'),
        ),
        migrations.AlterField(
            model_name='asset_category',
            name='min_asset_size',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Minimum Asset Size'),
        ),
    ]
