# Generated by Django 5.0.6 on 2024-07-05 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_alter_asset_category_max_asset_size_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='File_Types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'File Type',
                'verbose_name_plural': 'File Types',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='asset_category',
            name='required_file_types',
        ),
        migrations.AddField(
            model_name='asset_category',
            name='required_file_types',
            field=models.ManyToManyField(to='assets.file_types'),
        ),
    ]
