# Generated by Django 5.0.6 on 2024-07-06 06:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_file_types_remove_asset_category_required_file_types_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='License_Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_detail', models.CharField(max_length=1000, verbose_name='Term Detail')),
            ],
            options={
                'verbose_name': 'License Term',
                'verbose_name_plural': 'License Terms',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('size', models.DecimalField(decimal_places=2, max_digits=5)),
                ('asset', models.FileField(upload_to='')),
                ('price_for_regular_license', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_for_extended_license', models.DecimalField(decimal_places=2, max_digits=10)),
                ('title', models.CharField(max_length=200)),
                ('meta_description', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('verification_pending', 'Verification Pending'), ('published', 'Published'), ('rejected', 'Rejected')], max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.asset_category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asset',
                'verbose_name_plural': 'Assets',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='Asset_Preview_Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_preview_images', to='assets.asset')),
            ],
            options={
                'verbose_name': 'Asset Preview Image',
                'verbose_name_plural': 'Asset Preview Images',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='License_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('regular', 'Regular License'), ('extended', 'Extended License')], max_length=100, verbose_name='License Name')),
                ('Asset_Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.asset_category')),
                ('terms', models.ManyToManyField(to='assets.license_term')),
            ],
            options={
                'verbose_name': 'License Type',
                'verbose_name_plural': 'License Types',
                'ordering': ['name', 'Asset_Category'],
            },
        ),
    ]
