# Generated by Django 5.0.6 on 2024-07-06 09:00

import assets.helper_func
import private_storage.fields
import private_storage.storage.files
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_license_term_asset_asset_preview_images_license_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='license_type',
            options={'ordering': ['name'], 'verbose_name': 'License Type', 'verbose_name_plural': 'License Types'},
        ),
        migrations.RenameField(
            model_name='license_type',
            old_name='Asset_Category',
            new_name='asset_category',
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset',
            field=private_storage.fields.PrivateFileField(storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to=assets.helper_func.get_asset_path),
        ),
        migrations.AlterField(
            model_name='asset',
            name='size',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('verification_pending', 'Verification Pending'), ('published', 'Published'), ('rejected', 'Rejected')], default='draft', max_length=100),
        ),
        migrations.AlterField(
            model_name='asset_category',
            name='max_asset_size',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Maximum Asset Size(MB)'),
        ),
        migrations.AlterField(
            model_name='asset_category',
            name='min_asset_size',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Minimum Asset Size(MB)'),
        ),
        migrations.AlterField(
            model_name='asset_category',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Category Name'),
        ),
        migrations.AlterField(
            model_name='asset_preview_images',
            name='image',
            field=models.ImageField(upload_to=assets.helper_func.get_asset_preview_image_path),
        ),
        migrations.AlterField(
            model_name='license_term',
            name='term_detail',
            field=models.CharField(max_length=1000, unique=True, verbose_name='Term Detail'),
        ),
        migrations.AlterField(
            model_name='license_type',
            name='name',
            field=models.CharField(choices=[('regular_license', 'Regular License'), ('extended_license', 'Extended License')], max_length=100, verbose_name='License Name'),
        ),
    ]
