# Generated by Django 5.0.6 on 2024-07-07 07:46

import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_alter_license_type_options_and_more'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='keywords',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='size',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='asset_category',
            name='max_asset_size',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Maximum Asset Size(MB)'),
        ),
        migrations.AlterField(
            model_name='asset_category',
            name='min_asset_size',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Minimum Asset Size(MB)'),
        ),
    ]
