# Generated by Django 5.0.6 on 2024-07-07 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_asset_keywords_alter_asset_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='license_type',
            name='terms',
        ),
        migrations.RemoveField(
            model_name='license_type',
            name='asset_category',
        ),
        migrations.AlterField(
            model_name='asset',
            name='size',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.DeleteModel(
            name='License_Term',
        ),
        migrations.DeleteModel(
            name='License_Type',
        ),
    ]
