# Generated by Django 5.0.6 on 2024-07-08 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_remove_license_type_terms_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset_preview_images',
            options={'ordering': ['date_created'], 'verbose_name': 'Asset Preview Image', 'verbose_name_plural': 'Asset Preview Images'},
        ),
        migrations.RemoveField(
            model_name='asset',
            name='price_for_extended_license',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='price_for_regular_license',
        ),
    ]
