# Generated by Django 5.0.6 on 2024-07-10 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_alter_asset_preview_images_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('verification_pending', 'Verification Pending'), ('published', 'Published'), ('rejected', 'Rejected')], max_length=100),
        ),
        migrations.AlterField(
            model_name='file_types',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Name'),
        ),
    ]
