# Generated by Django 5.0.6 on 2024-07-10 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_alter_asset_status_alter_file_types_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('verification_pending', 'Verification Pending'), ('published', 'Published'), ('rejected', 'Rejected')], default='draft', max_length=100),
        ),
    ]
