# Generated by Django 5.0.6 on 2024-07-11 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0010_alter_asset_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='keywords',
            new_name='tags',
        ),
    ]
