# Generated by Django 5.0.6 on 2024-07-11 11:30

import django.db.models.deletion
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0011_rename_keywords_asset_tags'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='file_type',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='assets.file_types'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='asset',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
