# Generated by Django 5.0.6 on 2024-07-13 08:59

import assets.helper_func
import django.db.models.deletion
import private_storage.fields
import private_storage.storage.files
import taggit.managers
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0013_alter_asset_file_type'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset_category',
            name='required_file_types',
        ),
        migrations.AlterField(
            model_name='asset',
            name='file_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset',
            field=private_storage.fields.PrivateFileField(storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to=assets.helper_func.get_asset_path, verbose_name='Asset'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.asset_category', verbose_name='Asset Category'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Date Updated'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='description',
            field=models.TextField(verbose_name='Asset Description'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='meta_description',
            field=models.CharField(max_length=300, verbose_name='Asset Meta Description'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='size',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Asset Size'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('verification_pending', 'Verification Pending'), ('published', 'Published'), ('rejected', 'Rejected')], default='draft', max_length=100, verbose_name='Asset Status'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Asset Tags'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Asset Title'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='UUID'),
        ),
        migrations.AddField(
            model_name='asset_category',
            name='required_file_types',
            field=models.JSONField(default=list, verbose_name='List of Required File Types'),
        ),
        migrations.DeleteModel(
            name='File_Types',
        ),
    ]
