# Generated by Django 5.0.6 on 2024-07-13 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0014_remove_asset_category_required_file_types_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset_category',
            name='required_file_types',
            field=models.CharField(default='', max_length=1000, verbose_name='List of Required File Types'),
        ),
    ]
