# Generated by Django 5.0.6 on 2024-07-17 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0015_alter_asset_category_required_file_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='description',
            field=models.TextField(blank=True, default='Asset Description', verbose_name='Asset Description'),
        ),
    ]
