# Generated by Django 5.0.6 on 2024-07-19 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0016_alter_asset_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='title',
            field=models.CharField(max_length=120, verbose_name='Asset Title'),
        ),
    ]
