# Generated by Django 5.0.6 on 2024-07-23 09:58

import assets.helper_func
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0018_alter_asset_description_alter_asset_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset_preview_images',
            options={'ordering': ['-date_created'], 'verbose_name': 'Asset Preview Image', 'verbose_name_plural': 'Asset Preview Images'},
        ),
        migrations.AddField(
            model_name='asset',
            name='date_published',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date Published'),
        ),
        migrations.AlterField(
            model_name='asset_category',
            name='required_file_types',
            field=models.CharField(default='', help_text='file_type_1, file_type_2, file_type_3', max_length=1000, verbose_name='Required File Types'),
        ),
        migrations.AlterField(
            model_name='asset_preview_images',
            name='image',
            field=models.ImageField(upload_to=assets.helper_func.get_asset_preview_image_path, verbose_name='Preview Image'),
        ),
    ]
