# Generated by Django 5.0.6 on 2024-07-27 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0022_alter_asset_category_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset_preview_images',
            options={'ordering': ['date_created'], 'verbose_name': 'Asset Preview Image', 'verbose_name_plural': 'Asset Preview Images'},
        ),
    ]
