# Generated by Django 5.0.6 on 2024-07-30 17:47

import assets.helper_func
import assets.validators
import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0024_asset_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset_preview_images',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, quality=95, scale=None, size=[720, 923], upload_to=assets.helper_func.get_asset_preview_image_path, validators=[assets.validators.asset_preview_image_validator], verbose_name='Preview Image'),
        ),
    ]
