# Generated by Django 5.0.6 on 2024-07-30 18:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0025_alter_asset_preview_images_image'),
        ('orders', '0015_order_items_gst_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=3, verbose_name='Rating')),
                ('feedback', models.TextField(verbose_name='Feedback')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='assets.asset', verbose_name='Asset')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.orders')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Asset Feedback',
                'verbose_name_plural': 'Asset Feedbacks',
                'ordering': ['date_created'],
            },
        ),
    ]
