# Generated by Django 5.0.6 on 2024-07-30 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0026_assetfeedback'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assetfeedback',
            options={'ordering': ['-date_created'], 'verbose_name': 'Asset Feedback', 'verbose_name_plural': 'Asset Feedbacks'},
        ),
    ]
