# Generated by Django 5.0.6 on 2024-07-04 08:52

import accounts.helper_func
import accounts.validators
import django.contrib.auth.models
import django.core.validators
import django.utils.timezone
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(error_messages={'max_length': 'Username is too long, Max - 30.', 'unique': 'Username is not available.'}, help_text='a-z, 0-9 and underscore,dash & dot', max_length=30, unique=True, validators=[accounts.validators.username_validator], verbose_name='Username')),
                ('email', models.EmailField(error_messages={'unique': 'Email ID is not available.'}, help_text='Only for security reasons', max_length=254, unique=True, validators=[django.core.validators.EmailValidator], verbose_name='Email Id')),
                ('display_name', models.CharField(blank=True, error_messages={'max_length': 'Name is too long, max - 50.'}, max_length=50, null=True, verbose_name='Name')),
                ('profile_image', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=95, scale=None, size=[600, 600], upload_to=accounts.helper_func.get_profile_image_path, verbose_name='Profile Image')),
                ('uuid', models.UUIDField(blank=True, null=True, unique=True, verbose_name='UUID')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Is Verified')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
