# Generated by Django 5.0.6 on 2024-07-18 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_display_name_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='display_name',
        ),
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, error_messages={'max_length': 'Name is too long, max - 50.'}, max_length=50, null=True, verbose_name='Full Name'),
        ),
    ]
