# Generated by Django 5.0.6 on 2024-07-24 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_display_name_user_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address_area',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Address Area'),
        ),
        migrations.AddField(
            model_name='user',
            name='address_city',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Address City'),
        ),
        migrations.AddField(
            model_name='user',
            name='address_line_1',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Address Line 1'),
        ),
        migrations.AddField(
            model_name='user',
            name='address_line_2',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Address Line 2'),
        ),
        migrations.AddField(
            model_name='user',
            name='address_pincode',
            field=models.CharField(blank=True, default='', max_length=6, null=True, verbose_name='Address Pincode'),
        ),
        migrations.AddField(
            model_name='user',
            name='address_state',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Address State'),
        ),
        migrations.AddField(
            model_name='user',
            name='gst_number',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='GST Number'),
        ),
    ]
