# Generated by Django 5.0.6 on 2024-07-24 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_address_area_user_address_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='Phone Number'),
        ),
    ]
