# Generated by Django 5.0.6 on 2024-08-01 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homebanner',
            name='link_text',
            field=models.CharField(default='shop now', max_length=50, verbose_name='Link Button Text'),
            preserve_default=False,
        ),
    ]
