# Generated by Django 5.0.6 on 2024-08-03 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_homebanner_link_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homebanner',
            options={'ordering': ['date_created'], 'verbose_name': 'Home Banner', 'verbose_name_plural': 'Home Banners'},
        ),
    ]
