# Generated by Django 5.0.6 on 2024-07-16 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order_items',
            options={'ordering': ['-date_created'], 'verbose_name': 'Order Item', 'verbose_name_plural': 'Order Items'},
        ),
        migrations.AlterModelOptions(
            name='orders',
            options={'ordering': ['-date_created'], 'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
    ]
