# Generated by Django 5.0.6 on 2024-07-16 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_items_options_alter_orders_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='order_items',
            field=models.ManyToManyField(to='orders.order_items'),
        ),
        migrations.AlterField(
            model_name='order_items',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_items', to='orders.orders'),
        ),
    ]
