# Generated by Django 5.0.6 on 2024-07-16 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orders_order_items_alter_order_items_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='gst',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='sub_total',
            field=models.DecimalField(decimal_places=2, default=500, max_digits=20),
            preserve_default=False,
        ),
    ]
