# Generated by Django 5.0.6 on 2024-07-16 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orders_gst_orders_sub_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='gst',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='orders',
            name='sub_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='orders',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
