# Generated by Django 5.0.6 on 2024-07-16 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_orders_gst_alter_orders_sub_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='orders',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='orders',
            name='razorpay_payment_signature',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
