# Generated by Django 5.0.6 on 2024-07-17 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_orders_razorpay_order_id_orders_razorpay_payment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('canceled', 'Canceled'), ('failed', 'Failed')], default='pending', max_length=100),
        ),
    ]
