# Generated by Django 5.0.6 on 2024-07-22 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0006_alter_asset_license_asset_and_more'),
        ('orders', '0010_alter_orders_payment_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_items',
            name='license',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='license.license'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='user_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='orders',
            name='user_full_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='orders',
            name='user_phonenumber',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
