# Generated by Django 5.0.6 on 2024-07-22 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0006_alter_asset_license_asset_and_more'),
        ('orders', '0011_alter_order_items_license_alter_orders_user_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_items',
            name='license',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='license.asset_license'),
        ),
    ]
