# Generated by Django 5.0.6 on 2024-07-23 11:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0020_alter_asset_preview_images_image'),
        ('license', '0007_alter_asset_license_options_alter_license_options_and_more'),
        ('orders', '0013_alter_order_items_license'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_items',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.asset', verbose_name='Asset'),
        ),
        migrations.AlterField(
            model_name='order_items',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='order_items',
            name='license',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='license.license', verbose_name='License'),
        ),
        migrations.AlterField(
            model_name='order_items',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_items', to='orders.orders', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='order_items',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='address_area',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Address Area'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='address_city',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Address City'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='address_line_1',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Address Line 1'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='address_line_2',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Address Line 2'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='address_pincode',
            field=models.CharField(blank=True, default='', max_length=6, null=True, verbose_name='Address Pincode'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='address_state',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Address State'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name=' Date Created'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='gst',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='GST'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='gst_number',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='GST Number'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_items',
            field=models.ManyToManyField(to='orders.order_items', verbose_name='Order Items'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('canceled', 'Canceled'), ('failed', 'Failed')], default='pending', max_length=100, verbose_name='Order Status'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='other_razorpay_payment_details',
            field=models.JSONField(blank=True, null=True, verbose_name='Other Razorpay Payment Details'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='payment_on',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Payment Date'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Razorpay Order ID'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='razorpay_payment_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Razorpay Payment Fee'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Razorpay Payment ID'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='razorpay_payment_signature',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Razorpay Payment Signature'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='razorpay_payment_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Razorpay Payment Tax'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='sub_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Sub Total'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='total_payment_recieved',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Total Payment Recevied'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Total Price'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='user_email',
            field=models.EmailField(blank=True, default='', max_length=254, null=True, verbose_name='User Email'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='user_full_name',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='User Full Name'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='user_phonenumber',
            field=models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='User Phone Number'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='UUID'),
        ),
    ]
