# Generated by Django 5.0.6 on 2024-07-27 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_alter_order_items_asset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_items',
            name='gst',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='GST'),
        ),
        migrations.AddField(
            model_name='order_items',
            name='razorpay_payment_commision',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Razorpay Payment Commision'),
        ),
    ]
