# Generated by Django 5.0.6 on 2024-08-01 22:06

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_order_items_gst_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='user_phonenumber',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='User Phone Number'),
        ),
    ]
