# Generated by Django 5.0.6 on 2024-07-10 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0009_alter_asset_status_alter_file_types_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='License_Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_title', models.CharField(max_length=50, verbose_name='Term Title')),
                ('term_detail', models.CharField(max_length=2000, unique=True, verbose_name='Term Detail')),
            ],
            options={
                'verbose_name': 'License Term',
                'verbose_name_plural': 'License Terms',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('asset_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.asset_category')),
                ('license_terms', models.ManyToManyField(to='license.license_term')),
            ],
        ),
        migrations.CreateModel(
            name='Asset_License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.asset')),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='license.license')),
            ],
        ),
    ]
