# Generated by Django 5.0.6 on 2024-07-10 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license_term',
            name='term_title',
            field=models.CharField(max_length=45, verbose_name='Term Title'),
        ),
    ]
