# Generated by Django 5.0.6 on 2024-07-10 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0002_alter_license_term_term_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license_term',
            name='term_title',
            field=models.CharField(max_length=50, verbose_name='Term Title'),
        ),
    ]
