# Generated by Django 5.0.6 on 2024-07-10 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0010_alter_asset_status'),
        ('license', '0003_alter_license_term_term_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset_license',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='assets.asset'),
        ),
        migrations.AlterField(
            model_name='license',
            name='name',
            field=models.CharField(choices=[('regular_license', 'Regular License'), ('extended_license', 'Extended License'), ('commercial_license', 'Commercial License'), ('educational_license', 'Educational License')], max_length=100),
        ),
    ]
