# Generated by Django 5.0.6 on 2024-07-10 08:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0004_alter_asset_license_asset_alter_license_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset_license',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
