# Generated by Django 5.0.6 on 2024-07-13 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0014_remove_asset_category_required_file_types_and_more'),
        ('license', '0005_asset_license_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset_license',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='assets.asset', verbose_name='Asset'),
        ),
        migrations.AlterField(
            model_name='asset_license',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='asset_license',
            name='license',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='license.license', verbose_name='License'),
        ),
        migrations.AlterField(
            model_name='asset_license',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='license',
            name='asset_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.asset_category', verbose_name='Asset Category'),
        ),
        migrations.AlterField(
            model_name='license',
            name='license_terms',
            field=models.ManyToManyField(to='license.license_term', verbose_name='License Terms'),
        ),
        migrations.AlterField(
            model_name='license',
            name='name',
            field=models.CharField(choices=[('educational_license', 'Educational License'), ('regular_license', 'Regular License'), ('extended_license', 'Extended License'), ('commercial_license', 'Commercial License')], max_length=100, verbose_name='License Name'),
        ),
    ]
