# Generated by Django 5.0.6 on 2024-07-23 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0006_alter_asset_license_asset_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset_license',
            options={'ordering': ['-date_created'], 'verbose_name': 'Asset License', 'verbose_name_plural': 'Asset Licenses'},
        ),
        migrations.AlterModelOptions(
            name='license',
            options={'ordering': ['-pk'], 'verbose_name': 'License', 'verbose_name_plural': 'Licenses'},
        ),
        migrations.AlterModelOptions(
            name='license_term',
            options={'ordering': ['-pk'], 'verbose_name': 'License Term', 'verbose_name_plural': 'License Terms'},
        ),
        migrations.AlterField(
            model_name='asset_license',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='license',
            name='name',
            field=models.CharField(choices=[('educational_license', 'Educational License'), ('personal_license', 'Personal License'), ('regular_license', 'Regular License'), ('extended_license', 'Extended License'), ('commercial_license', 'Commercial License')], max_length=100, verbose_name='License Name'),
        ),
        migrations.AlterField(
            model_name='license_term',
            name='term_detail',
            field=models.CharField(max_length=2000, verbose_name='Term Detail'),
        ),
    ]
