# Generated by Django 5.0.6 on 2024-07-27 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0007_alter_asset_license_options_alter_license_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset_license',
            options={'ordering': ['date_created'], 'verbose_name': 'Asset License', 'verbose_name_plural': 'Asset Licenses'},
        ),
    ]
