# Generated by Django 5.0.6 on 2024-07-30 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0008_alter_asset_license_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='license',
            options={'ordering': ['pk'], 'verbose_name': 'License', 'verbose_name_plural': 'Licenses'},
        ),
    ]
